### ISSUE TITLE
some bug about utf-8 by luaopswap

### ISSUE THREAD

**Issue by yjtortor** [viruscamp/luadec#36]
转换之后明显会出现UTF-8乱码。

**Comment by yjtortor** [comment]
转换OP,LUAOPSWAP.TXT也不写一个格式说明的。。
直接int op2op[OP2OP_SIZE]={XX,XX,XX,XX}就行了。
LUAOPSWAP.TXT格式为
新的OPCODE OPCODENAME
4   MOVE
5  LOADK

**Comment by yjtortor** [comment]
char* DecompileConstant(const Proto* f, int i) {
	const TValue* o = &f->k[i];
	int tmp = ttype(o);
	switch (ttype(o)) {
	case LUA_TBOOLEAN:
		return strdup(bvalue(o)?"true":"false");
	case LUA_TNIL:
		return strdup("nil");
#if LUA_VERSION_NUM == 501 || LUA_VERSION_NUM == 502
	case LUA_TNUMBER:
	{
		char* ret = (char*)calloc(128, sizeof(char));
		sprintf(ret, LUA_NUMBER_FMT, nvalue(o));
		return ret;
	}
	case LUA_TSTRING:case LUA_TLNGSTR: --modify
		return DecompileString(o);
#endif

**Comment by viruscamp** [comment]
No encoding problem.
New -template argument for luaopswap in e53d52860bf0080b9ade4c6df2b4af48e8484d3d
LUA_TLNGSTR in 5.2 fixed in 392358cc4a915f47fca2de7ab9bcec18c9fd0175
