### ISSUE TITLE
setlist bug

### ISSUE THREAD

**Issue by yjtortor** [viruscamp/luadec#37]
3 [-]: NEWTABLE  R6 16 0      ; R6 := {}
    4 [-]: LOADK     R7 K1        ; R7 := "a"
    5 [-]: LOADK     R8 K2        ; R8 := "b"
    6 [-]: LOADK     R9 K3        ; R9 := "c"
    7 [-]: LOADK     R10 K4       ; R10 := "d"
    8 [-]: LOADK     R11 K5       ; R11 := "l"
    9 [-]: LOADK     R12 K6       ; R12 := "f"
   10 [-]: LOADK     R13 K7       ; R13 := "g"
   11 [-]: LOADK     R14 K8       ; R14 := "i"
   12 [-]: LOADK     R15 K9       ; R15 := "j"
   13 [-]: LOADK     R16 K10      ; R16 := "k"
   14 [-]: LOADK     R17 K4       ; R17 := "d"
   15 [-]: LOADK     R18 K11      ; R18 := "e"
   16 [-]: LOADK     R19 K12      ; R19 := "z"
   17 [-]: LOADK     R20 K13      ; R20 := "y"
   18 [-]: LOADK     R21 K14      ; R21 := "h"
   19 [-]: LOADK     R22 K15      ; R22 := "x"
   20 [-]: SETLIST   R6 16 1      ; R6[0] to R6[15] := R7 to R22 ; R(a)[(c-1)*FPF+i] := R(a+i), 1 <= i <= b, a=6, b=16, c=1, FPF=50     --NEWTABLE  already close!

**Comment by viruscamp** [comment]
Not a bug.
If it appears while processing a stripped file, it is the bug of local guessing.
